{%set name = "tika" %}
{%set version = "1.13.1" %}
{%set hash_type = "sha256" %}
{%set hash_val = "9d32ecb41206ee7f1f3960946d6a79b18f9711162ce1a116bdd2700fcf7ddd2f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  preserve_egg_dir: True
  entry_points:
    - tika-python = tika.tika:main

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - requests

test:
  imports:
    - tika
    - tika.tests

  commands:
    - tika-python --help

about:
  home: http://github.com/chrismattmann/tika-python
  license: Apache 2.0
  summary: 'Apache Tika Python library'

extra:
  recipe-maintainers:
    - pmlandwehr
    - chrismattmann
