{% set name = "tika" %}
{% set version = "1.18" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "9dc96187e15eca6b90ed9356e0d4c1be173fc1111e0b607af2117134a964cd5c" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  preserve_egg_dir: True
  entry_points:
    - tika-python = tika.tika:main

  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - setuptools
    - requests

test:
  imports:
    - tika
    - tika.tests

  commands:
    - tika-python --help

about:
  home: http://github.com/chrismattmann/tika-python
  license_file: LICENSE.txt
  license: Apache 2.0
  license_family: Apache
  summary: 'Apache Tika Python library'
  doc_url: https://github.com/chrismattmann/tika-python
  dev_url: https://github.com/chrismattmann/tika-python

extra:
  recipe-maintainers:
    - pmlandwehr
    - chrismattmann
