{% set name = "tika" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/chrismattmann/{{ name }}-python/archive/refs/tags/{{ version }}.tar.gz
    sha256: ec234cbf5c192612cb50793ff2cd6b80c7be5f18688e6b19e4e1d2490e07630f
    patches:
      - patches/fix_test.patch

build:
  entry_points:
    - tika-python = tika.tika:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - requests

# External URL blocked by Wikimedia (403 Forbidden)
{% set deselected_tests = [
  "--deselect=tika/tests/test_ssl_link.py::CreateTest::test_url",
  "--deselect=tika/tests/test_tika.py::CreateTest::test_remote_jpg",
  "--deselect=tika/tests/test_tika.py::CreateTest::test_remote_html"
]%}
test:
  source_files:
    - tika/tests
  imports:
    - tika
    - tika.tests
  requires:
    - pip
    - pytest
    - pytest-benchmark >=3.2.2
    - openjdk
  commands:
    - pip check
    - tika-python --help
    - pytest -v {{ deselected_tests | join(" ")}}

about:
  home: https://github.com/chrismattmann/tika-python
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: Apache Tika Python library
  description: |
    A Python port of the Apache Tika library that makes Tika available using the Tika REST Server.
    This makes Apache Tika available as a Python library, installable via Setuptools, Pip and Easy Install.
  doc_url: https://github.com/chrismattmann/tika-python
  dev_url: https://github.com/chrismattmann/tika-python

extra:
  recipe-maintainers:
    - pmlandwehr
    - chrismattmann
