travis:
  secure:
    BINSTAR_TOKEN: BsKCalsSrZGaDEBmsdacKitZ9F9fakgdESDPzgviHDZ2VKmNto5izuzCllDkq8Kd0nESwqHMHwwzTpCG87EHYjk9kxQeluWbINJsIFhBpHmRMZFwxKHaZdHtEFV5qd35bV8KC2M/wWYGPn6xSvzc20beqVRurI5DkbALsB+8xVKvUKXpZyVstT6qAUVnouxnGYF7edkGTQEHDJEOLNaFSHKH2X7JEeKV5B08bhHXzX3atas0WmRONLBindwOLp11eG8LF7t2BPZ/UV1J9iCMI0pmmSr/HyCFNWQWxnMvSwgNvzzeHrKfXnkCo8SLvyGb6Gh9+NJhrD78jal8KtlvFeYfotxz131+Qfvu2xWMzWtpKoQkilqMiFakg52EjL65cLMLnAmtg59/BUUe2ZgniYNxHdk4fCaBe3dWmro6TV+crAj20I6oq+c9MycBq650qXoQAOmc85AfLrbi5B0ixRQSmdYpuiVWI76llWEgiA3qJir/UkSMkASdAy7yK+13WCBWa3jS8xJXW6ynaxoIIn4QfeNI4+RmUCNVblh7sVP9IHQ913xvjwIeDXTwxFwp+Cq3elv1DeghomU4mr8LENWqCsn0/NYXL/vsBCAgMCE8Y93iFT5kVoytziowAcfvxNNRfVrFVZdhKZ9w8dY1Wqr2JPxzx4KOXw3wgW7mcs4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
