travis:
  secure:
    BINSTAR_TOKEN: cg7Qr3aLnYcty6nObGVdhf/q91vu3cwpk+Fz1Lg2b6R84uq75mh1tEJixKRNgU+klP67+6PU40ZgXkdh76/bWRZcBQnq2Kpvc5Ft8xHSujo3q5hi4L+7nGpdIEkQHzVkITkD9ghXlEIzpq6lfNxVEIJFp7MNtSvprGLkYdTFf2xbPU9M2/Ov+Ivh6ktcmZ17pVz8hYtA0DPSanw+eH01g6vA2yoqjNPsM7hQRFaRLlhomxpJnDjEiKJb/JWd5TjXTa9hWWI3JH68OFm58k0xxys6tcN4JrJKIMNP557sH6Gckdk50iJxKf4r+FAnZ9ad9jm3hjcldJRCj0FoBnEtECypU7gt0CqbOiImuO/LTLV4TGy+W0CGjBnMUX7uxDRrF3QmE1wdTOroXDtpN3m8lbf4ASmrvUk/Z6BbcfdMCv7TAMekqki0jU8CO72m2BGRvL4r7rCavS1OAlqncvdO9C8VYtrqqdVS65axfPRK48On4qCENQRt04cmHh+ZaDK6AbTbVdbDzSfskii8NWzbI/DPvATzgYxk1xo+9sYuboJsIoEVvzjj+SZHS2kqr6Qkl7geJCsXDeS2Ky8jzYfMgprvAcEqpnc9RIjHkfvCExV2w5bLA9IlX8XfZNry+VCs+h/7XA+QWnxnZNrx0maUxmT1u0gfs3+XItkjs9tIFVI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
