travis:
  secure:
    BINSTAR_TOKEN: ih9Z+Y37wu4dnz/DwOCGUg93301wSgGx43NZM9L1Z5xXGCFP8ye7XYd0dvbLV/V/ytq5O9hh9ENLZIgA5GUut0wsiU3t3vz7Oyi5wIEFfuROx19725ZUxlk8ENO9AVxE8D4T9bTJmLbU88oDRaty0OcUJ7tvVew/woNWciIOWjGU7pIX1fN12b6oJqcZSn0x2GCEqNqbiBwSQTBIcRyuPOaY6q17Y0oYMJATn5ooXM+EhCWRhoUDYhpQDNdklBmw0jlQhIsTuKn9xoAZ7S13H8pgnAug1IXJwAD/i26Le/zMnij4D6ZwfdzNEx5o/GNfibBaABznVi1/+OV1FUEPAvNEWqU6HuwqlrXE0tcglqEdvLTcVwt4Kwzfxti1E0nJe21A5U9LUooyHQF0G08UKHZTX91hn0I0KHVSjZkeTxHHyWXS1DNHpUdfsoCZ24HQ8t2gBS2TlH6BCpROwqPnB6C6KMXnFpMBYvBnvVF4WiqNkSMV7GA0DOCchvwiPYGFiMIaFdIMFvsqLfvXKRyopeqUqTtNEKJmlRYtAdy534z3QqW/9fSQ5jTgQWwZVIg8A7ekkZD5Kb9QurnP8o1THfxBheV0Nrapgzt6BDmViqjPWi/nw+4IB/ErtmwrQerL5zHSKQes68cIYo4igvx68YsX0iEFTQYs3qAnI5dUDAU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
